export const products = [
  {
    id: 1,
    title: "Website & blog",
    desc: "Personal website & blog",
    techs: ["MongoDB", "Express", "React", "NodeJS", "Cloudinary"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655149324/manuel/marisela_hj00nt.png",
    linkGit:
      "https://github.com/Manuelhhinojosa/MariselaLF-Personal-website-portfolio",
    linkApp: "https://mariselafierro.netlify.app",
  },
  {
    id: 2,
    title: "API",
    desc: "REST API",
    techs: ["MongoDB", "Express", "NodeJS", "JS", "Vercel"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655041118/manuel/api_jp41gw.webp",
    linkGit: "https://github.com/Manuelhhinojosa/marisela-fierro-api",
    linkApp: "https://marisela-api.vercel.app/posts",
  },
  {
    id: 3,
    title: "OK200 Web Programmer",
    desc: "Provides software updates to electronic instruments",
    techs: ["Express", "React", "NodeJS", "Typescript", "SASS"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1713514030/manuel/Screen_Shot_2024-04-19_at_3.06.55_PM_luvy3y.png",
    linkGit: "https://github.com/scottc11/ok-web-programmer",
    linkApp: "https://underconstructionmhh.netlify.app/",
  },
  {
    id: 4,
    title: "ChatApp",
    desc: "Live chat app",
    techs: ["Socket IO", "React router v6", "Json web token", "JS", "SASS"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1669734791/manuel/Screen_Shot_2022-11-29_at_10.12.57_AM_yktoik.png",
    linkGit: "https://github.com/Manuelhhinojosa/chat-app-client",
    linkApp: "https://underconstructionmhh.netlify.app",
  },
  {
    id: 5,
    title: "API",
    desc: "REST API",
    techs: ["MongoDB", "Express", "NodeJS", "JS", "Atlas' MongoDB"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655041118/manuel/api_jp41gw.webp",
    linkGit: "https://github.com/Manuelhhinojosa/chatAppApi",
    linkApp: "https://underconstructionmhh.netlify.app",
  },
  {
    id: 6,
    title: "Yelpcamp",
    desc: "A Yelp-like CRUD app for campsites",
    techs: ["Express", "Location services", "Map Serivices"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038544/manuel/yelpcamp_lispaw.png",
    linkGit: "https://github.com/Manuelhhinojosa/yelpcamp-MEN",
    linkApp: "https://yelpcamp-murex-ten.vercel.app/home",
  },
  {
    id: 7,
    title: "Applants",
    desc: "An Instagram-like CRUD application",
    techs: ["MongoDB", "Express", "NodeJS", "HTML", "JS"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038101/manuel/applants_xbwao1.png",
    linkGit:
      "https://github.com/Manuelhhinojosa/applants-Mongo-Express-HTML-CSS-JS",
    linkApp: "https://applants.vercel.app/applants",
  },
  {
    id: 8,
    title: "Movie Fight",
    desc: "Compares two movies collecting data from a pulic API",
    techs: ["Netlify", "Axios", "JSON", "Public API"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037769/manuel/movieFight_nrycmy.png",
    linkGit:
      "https://github.com/Manuelhhinojosa/movieCompareApp-HTML-CSS-JS-API",
    linkApp: "https://moviecomparemhh.netlify.app",
  },
  {
    id: 9,
    title: "Weather app",
    desc: "Provides weather conditions collecting data from an API",
    techs: ["Netlify", "Axios", "JSON", "Public API"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1713319294/manuel/Screen_Shot_2024-04-17_at_9.01.13_AM_ru4xnd.png",
    linkGit: "https://github.com/Manuelhhinojosa/weatherApp",
    linkApp: "https://weathermhh.netlify.app/",
  },
  {
    id: 10,
    title: "Secret message app",
    desc: "Allows to share secret a messages using an URL with a secret messaged encoded",
    techs: ["JS", "Node", "JSON"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1713319557/manuel/Screen_Shot_2024-04-17_at_9.05.03_AM_kep5uk.png",
    linkGit: "https://github.com/Manuelhhinojosa/secretMessage-HTML-JS",
    linkApp: "https://secretmessagemhh.netlify.app",
  },
  {
    id: 11,
    title: "Maze",
    desc: "Maze game",
    techs: ["HTML", "CSS", "JS", "Netlify", "Matter-JS"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1676314224/manuel/Screen_Shot_2023-02-13_at_1.49.11_PM_id6kqw.png",
    linkGit: "https://github.com/Manuelhhinojosa/maze-HTML-JS",
    linkApp: "https://mazemhh.netlify.app",
  },
  {
    id: 12,
    title: "Hangman",
    desc: "Classic Hangman game",
    techs: ["HTML", "CSS", "JS", "Netlify", "Git"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655040269/manuel/Screen_Shot_2022-06-12_at_9.24.13_AM_ox2wg8.png",
    linkGit: "https://github.com/Manuelhhinojosa/hangman-HTML-JS",
    linkApp: "https://hangmanmhh.netlify.app",
  },
  {
    id: 13,
    title: "Connect Four",
    desc: "Classic Connect Four game",
    techs: ["HTML", "CSS", "JS", "Netlify", "DOM manipulation"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037011/manuel/connectFour_rqb0fo.png",
    linkGit: "https://github.com/Manuelhhinojosa/connectFour",
    linkApp: "https://connectfourmhh.netlify.app",
  },
  {
    id: 14,
    title: "Timer app",
    desc: "Interactive timer app",
    techs: ["HTML", "CSS", "JS", "Netlify", "git"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037217/manuel/timerApp_kprfnv.png",
    linkGit: "https://github.com/Manuelhhinojosa/timerApp-HTML-CSS-JS",
    linkApp: "https://timermhh.netlify.app",
  },
  {
    id: 15,
    title: "Hangman 2",
    desc: "Classic Hangman game",
    techs: ["React", "React router V6", "HTML", "Typescript", "SASS"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1681244219/manuel/Screen_Shot_2023-04-11_at_4.15.48_PM_rlhpvi.png",
    linkGit: "https://github.com/Manuelhhinojosa/hangman-React-Typescript-SASS",
    linkApp: "https://hangmanmhh.vercel.app",
  },
  {
    id: 16,
    title: "Taskiky",
    desc: "An app that helps you keep your tasks organized",
    techs: ["React", "Typescript", "Heroku", "SASS", "HTML"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1681244395/manuel/Screen_Shot_2023-04-11_at_4.19.26_PM_ri7vbq.png",
    linkGit: "https://github.com/Manuelhhinojosa/taskify-React-Typescript-SASS",
    linkApp: "https://taskifymhh.vercel.app",
  },
  {
    id: 17,
    title: "HTML & CSS website",
    desc: "A website created using only HTML and CSS",
    techs: ["HTML", "CSS", "Netlify", "Git", "Github"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037938/manuel/website_efsv77.png",
    linkGit: "https://github.com/Manuelhhinojosa/HTML-CSS-based-website",
    linkApp: "https://restaurantmhh.netlify.app",
  },
];
