export const products = [
  {
    id: 1,
    title: "Artist / Academic's website & blog",
    desc: "Personal website",
    techs: [
      "JS ",
      "NodeJS ",
      "MongoDB ",
      "Mongoose ",
      "Atlas ",
      "Express ",
      "React ",
      "Heroku ",
      "Cloudinary ",
      "EmailJS ",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655149324/manuel/marisela_hj00nt.png",
    linkGit: "https://github.com/Manuelhh/marisela-website",
    linkApp: "https://mariselalfierro.herokuapp.com/",
  },
  {
    id: 2,
    title: "OK200 Web Programmer",
    desc: "Provides software updates to electronic instruments",
    techs: [
      "HTML",
      "CSS",
      "JS",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "React",
      "Typescript",
      "SASS",
      "Cloudinary",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1669734791/manuel/Screen_Shot_2022-11-29_at_10.12.57_AM_yktoik.png",
    linkGit: "https://github.com/scottc11/ok-web-programmer",
    linkApp: "https://github.com/scottc11/ok-web-programmer",
  },
  {
    id: 3,
    title: "Yelpcamp",
    desc: "A Yelp-like web CRUD application for campsites",
    techs: [
      "JS",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "Heroku",
      "Location services",
      "Map Serivices",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038544/manuel/yelpcamp_lispaw.png",
    linkGit: "https://github.com/Manuelhh/yelpcamp-app",
    linkApp: "https://mh-yelpcamp.herokuapp.com/",
  },
  {
    id: 4,
    title: "Public REST API",
    desc: "An application programming interface made publicly available for software developers",
    techs: [
      "Typescript",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "JSON",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655041118/manuel/api_jp41gw.webp",
    linkGit: "https://github.com/Manuelhh/rest-api",
    linkApp: "https://github.com/Manuelhh/rest-api",
  },
  {
    id: 5,
    title: "Applants",
    desc: "An Instagrma-like web CRUD application",
    techs: [
      "HTML",
      "CSS",
      "JS",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "Heroku",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038101/manuel/applants_xbwao1.png",
    linkGit: "https://github.com/Manuelhh/applants",
    linkApp: "https://applants.herokuapp.com",
  },
  {
    id: 6,
    title: "Movie Fight",
    desc: "Compares two given movies collecting data from a pulic API",
    techs: ["HTML", "CSS", "JS", "Netlify", "Axios", "JSON"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037769/manuel/movieFight_nrycmy.png",
    linkGit: "https://github.com/Manuelhh/movie-fight-app",
    linkApp: "https://superlative-bunny-0d9bb2.netlify.app",
  },

  {
    id: 7,
    title: "HTML & CSS based website",
    desc: "A website created using only HTML and CSS",
    techs: ["HTML", "CSS", "Netlify"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037938/manuel/website_efsv77.png",
    linkGit: "https://github.com/Manuelhh/html-css-website",
    linkApp: "https://competent-easley-7a403a.netlify.app",
  },
  {
    id: 8,
    title: "Hangman",
    desc: "Classic Hangman game",
    techs: ["HTML", "CSS", "JS", "Github Pages", "DOM manipulation"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655040269/manuel/Screen_Shot_2022-06-12_at_9.24.13_AM_ox2wg8.png",
    linkGit: "https://github.com/Manuelhh/hangman",
    linkApp: "https://optimistic-northcutt-494969.netlify.app",
  },
  {
    id: 9,
    title: "Connect Four",
    desc: "Classic Connect Four game",
    techs: ["HTML", "CSS", "JS", "Netlify", "DOM manipulation"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037011/manuel/connectFour_rqb0fo.png",
    linkGit: "https://github.com/Manuelhh/connect-four",
    linkApp: "https://cocky-goodall-e34f0c.netlify.app",
  },

  {
    id: 10,
    title: "Timer",
    desc: "Interactive timer app",
    techs: ["HTML", "CSS", "JS", "Github Pages"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037217/manuel/timerApp_kprfnv.png",
    linkGit: "https://github.com/Manuelhh/timer-app",
    linkApp: "https://manuelhh.github.io/timer-app/",
  },
  {
    id: 11,
    title: "Maze",
    desc: "Maze game",
    techs: ["Matter-JS ", "HTML ", "CSS ", "JS ", "Netlify "],
    img: "https://res.cloudinary.com/mangud/image/upload/v1676314224/manuel/Screen_Shot_2023-02-13_at_1.49.11_PM_id6kqw.png",
    linkGit: "https://github.com/Manuelhh/maze",
    linkApp: "https://dynamic-otter-6969a8.netlify.app",
  },
  {
    id: 12,
    title: "Hangman",
    desc: "Classic Hangman game",
    techs: ["React", "React router V6", "Typescript", "SASS"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1681244219/manuel/Screen_Shot_2023-04-11_at_4.15.48_PM_rlhpvi.png",
    linkGit: "https://github.com/Manuelhh/Hangman2",
    linkApp: "https://cool-gaufre-f11c28.netlify.app",
  },
  {
    id: 13,
    title: "Taskiky",
    desc: "A web based application that helps you keep your tasks organized",
    techs: ["React", "Typescript", "SASS", "HTML", "DOM manipulation"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1681244395/manuel/Screen_Shot_2023-04-11_at_4.19.26_PM_ri7vbq.png",
    linkGit: "https://github.com/Manuelhh/taskify",
    linkApp: "https://incandescent-rolypoly-505b3f.netlify.app",
  },
];
